import Foundation

/// Accessibility identifiers shared by page objects and tests.
/// Names follow `<screen>.<element>` (see the test guide). Page objects read only this list.
/// If `app-tests/IDENTIFIERS.md` uses a different string, change it here — do not fork names in screens.
enum PPID {
    static let auth = "signIn.signIn"
    static let authEmail = "signIn.email"
    static let authPassword = "signIn.password"
    static let authSignIn = "signIn.signIn"
    static let authForgotPassword = "signIn.forgotPassword"
    static let authError = "auth.error"
    static let authResetPassword = "passwordReset.done"
    static let authResetEmail = "passwordReset.emailAddress"
    static let authResetSend = "passwordReset.sendResetLink"
    static let authSignOutConfirm = "auth.signOut.confirm"

    static let home = "home.refresh"
    static let homeGreeting = "home.greeting"
    static let homeDate = "home.date"
    static let homeRefresh = "home.refresh"
    static let homeNotifications = "home.notifications"
    static let homeAvatar = "home.avatar"
    static let homeMainMenu = "home.mainMenu"
    static let homeCustomise = "home.customize"
    static let homeCustomiseDone = "home.customiseDone"
    static let homeAddQuickAction = "home.addQuickAction"
    static let homeSeeAll = "home.seeAll"
    static let homeUpNextEmpty = "home.upNext.empty"
    static let homeOverviewSettings = "home.overviewSettings"
    static let homeOverviewSettingsDone = "home.overviewSettings.done"
    static let homeEditTabBar = "home.editTabBar"
    static let homeEditTabBarDone = "home.editTabBar.done"
    static let homeWarnings = "home.warnings"
    static let homeTasksDueToday = "home.tasksDueToday"

    static func homeQuickAction(_ id: String) -> String { "home.row.\(id)" }

    static let mainMenu = "mainMenu.screen"
    static let mainMenuDone = "mainMenu.done"
    static func mainMenuRow(_ id: String) -> String { "mainMenu.row.\(id)" }
    static func mainMenuQuick(_ id: String) -> String { "mainMenu.quick.\(id)" }

    static let more = "mainMenu.signOut"
    static let moreClose = "more.close"
    static func moreRow(_ id: String) -> String { "more.row.\(id)" }
    static func moreQuick(_ id: String) -> String { "more.quick.\(id)" }

    static let navBack = "nav.back"
    static let sheetDone = "sheet.done"
    static let sheetClose = "sheet.close"

    static func tab(_ name: String) -> String {
        let slug = name
            .lowercased()
            .replacingOccurrences(of: " ", with: "")
        return "tab.\(slug)"
    }

    static let tabHome = "tab.home"
    static let tabMore = "tab.more"

    static let notifications = "notifications.screen"
    static let notificationsMarkRead = "notifications.markRead"
    static let profile = "profile.screen"
    static let profileName = "profile.name"

    static let projects = "projects.screen"
    static let projectsAdd = "projects.add"
    static let projectsSearch = "projects.search"
    static let projectsEmpty = "projects.empty"
    static let projectsSave = "projects.save"
    static let projectsValidation = "projects.validation"
    static let projectsReference = "projects.reference"
    static let projectsSiteName = "projects.siteName"
    static let projectsAddress1 = "projects.address1"
    static let projectsTown = "projects.town"
    static let projectsPostcode = "projects.postcode"
    static let projectsExpandAddress = "projects.expandAddress"
    static let projectsClient = "projects.client"
    static let projectsManagers = "projects.managers"
    static let projectDetail = "projectDetail.screen"
    static let projectDetailEdit = "projectDetail.edit"
    static let projectDetailEndDate = "projectDetail.endDate"
    static let projectDetailSave = "projectDetail.save"
    static let projectDetailTasks = "projectDetail.tasks"
    static let projectDetailSchedule = "projectDetail.schedule"
    static let projectDetailDocuments = "projectDetail.documents"
    static let projectDetailHealthSafety = "projectDetail.healthSafety"
    static let projectDetailVariations = "projectDetail.variations"

    static let smallWorks = "smallWorks.screen"
    static let smallWorksAdd = "smallWorks.add"
    static let smallWorksSave = "smallWorks.save"
    static let smallWorksStatus = "smallWorks.status"
    static let smallWorksReference = "smallWorks.reference"
    static let smallWorksSiteName = "smallWorks.siteName"

    static let variations = "variations.screen"
    static let variationsAdd = "variations.add"
    static let variationsSave = "variations.save"
    static let variationsHeading = "variations.heading"
    static let variationsDescription = "variations.description"
    static let variationsLabourHours = "variations.labourHours"
    static let variationsTrade = "variations.trade"
    static let variationsStatus = "variations.status"
    static let variationsVONumber = "variations.voNumber"

    static let tasks = "tasks.screen"
    static let tasksAdd = "tasks.add"
    static let tasksTitle = "tasks.title"
    static let tasksDueDate = "tasks.dueDate"
    static let tasksAssignee = "tasks.assignee"
    static let tasksSave = "tasks.save"
    static let tasksComplete = "tasks.complete"

    static let schedule = "schedule.screen"
    static let scheduleAdd = "schedule.add"
    static let scheduleSave = "schedule.save"
    static let scheduleOperative = "schedule.operative"
    static let scheduleProject = "schedule.project"
    static let scheduleFullDay = "schedule.fullDay"
    static let schedulePartDay = "schedule.partDay"
    static let dailyOverview = "schedule.dailyOverview"
    static let weeklyReport = "schedule.weeklyReport"

    static let timesheets = "timesheets.screen"
    static let timesheetsAdd = "timesheets.add"
    static let timesheetsHours = "timesheets.hours"
    static let timesheetsSubmit = "timesheets.submit"
    static let timesheetsApprove = "timesheets.approve"
    static let timesheetsReject = "timesheets.reject"
    static let timesheetsStatus = "timesheets.status"
    static let timesheetsPendingRow = "timesheets.pendingRow"

    static let leave = "leave.screen"
    static let leaveRequest = "leave.request"
    static let leaveStart = "leave.startDate"
    static let leaveEnd = "leave.endDate"
    static let leaveSubmit = "leave.submit"
    static let leaveApprove = "leave.approve"
    static let leaveReject = "leave.reject"
    static let leaveBalance = "leave.balance"
    static let leaveStatus = "leave.status"
    static let leavePendingRow = "leave.pendingRow"

    static let warnings = "warnings.screen"
    static let warningsAdd = "warnings.add"
    static let warningsOperative = "warnings.operative"
    static let warningsType = "warnings.type"
    static let warningsIssue = "warnings.issue"
    static let warningsCount = "warnings.count"

    static let peopleOperatives = "people.operatives"
    static let peopleManagers = "people.managers"
    static let peopleSubcontractors = "people.subcontractors"
    static let peopleManageUsers = "people.manageUsers"
    static let peopleAddUser = "people.addUser"
    static let peopleFirstName = "people.firstName"
    static let peopleSurname = "people.surname"
    static let peopleEmail = "people.email"
    static let peopleRole = "people.role"
    static let peopleSave = "people.save"
    static let peopleValidation = "people.validation"
    static let peopleAddSubcontractor = "people.subcontractors.add"

    static let libraryClients = "library.clients"
    static let libraryClientsAdd = "library.clients.add"
    static let libraryClientName = "library.clients.name"
    static let libraryClientsSave = "library.clients.save"
    static let libraryClientsSearch = "library.clients.search"
    static let libraryJobTypes = "library.jobTypes"
    static let libraryQualifications = "library.qualifications"
    static let libraryMyQualifications = "library.myQualifications"
    static let libraryWholesalers = "library.wholesalers"
    static let libraryMaterials = "library.materials"
    static let librarySave = "library.save"

    static let siteAudit = "siteAudit.screen"
    static let siteAuditStart = "siteAudit.start"
    static let siteAuditNotes = "siteAudit.notes"
    static let siteAuditSave = "siteAudit.save"
    static let siteMap = "siteMap.screen"

    static let settings = "settings.screen"
    static let settingsOrganisationHub = "settings.organisationHub"
    static let settingsWorkingHours = "settings.workingHours"
    static let settingsAnnualLeave = "settings.annualLeave"
    static let settingsScheduleOptions = "settings.scheduleOptions"
    static let settingsCompanyDetails = "settings.companyDetails"
    static let settingsWarnings = "settings.warnings"
    static let settingsPaymentRuns = "settings.paymentRuns"
    static let settingsHelp = "settings.help"
    static let help = "help.screen"
    static let helpSupportEmail = "help.supportEmail"
}
